# Photosynthesis is Like an Engine

No, it is not. Actually photosynthesis is the exact opposite of an engine. Where an engine burns, photosynthesis unburns. Our combustion engines today burn very recent or very old products of photosynthesis.

But as an engine converts some form of energy into another, with a very rigorous process and a very standard set of parts, so does photosynthesis.

## Similarities

So, for example, as a combustion engine has a core concept involving:

- a specific chemical reaction that releases heat (CH + O2 --> CO2 + H2O),
- A tank to store the fuel,
- a carburator and cylinders in which the fuel is burnt
- a crankshaft that converts the up and down motion from the pistons into rotational motion.

So photosynthesis has:

- a specifical chemical reaction that is powered by light (CO2 + H2O --> CH2O + O2) ... noticed the similarity?
- An antenna structure that harvest the sunlight (that contains the green clorophyll, when you look around and see something green you are probably looking at this),
- An energy transfer cascade from light to potential energy stored in molecules that culminates with the production of sugar.

And as a combustion engine, photosynthesis has many modifications and adaptations that can be done to this simple structure.

## Implementation of the concept

There are many combustion engine and even if some of them sound "better" than others, they are often build with a specific purpose and hardly interchangeable. Even if an F1 engine sounds better than a small city car engine. Though you would not move an F1 engine in a city car, a city car engine in a truck and a truck engine in an F1 car. None of the possible combination seems good.

So does photsynthesis. There are many photosynthesis, some sounds better than other. But indeed, in every plant, photosynthesis is optimized for the environmental conditions that that plant met during evolution and that it is likely to meet in the future. You would not move a model of photosynthesis from one plant to the other... Or would we?
