# Two Drastic Adaptations

Every plant species has adapted photosynthesis to its needs with small modification to its photosynthetic machinery. But we know also two drastic adaptation of the photosynthetic machinery that have been introduced recurrently during evolution by multiple plant species. Those two drastic adaptations of photosynthesis are called C4 and CAM, the plants that implement those types of photosynthesis grow and thrive in hot and dry weather.

## Nuisance of hot weather

Hot and dry weather is very hostile to photosynthesis. Even if this might look like an obvious effect, understanding why hot weather is hostile to photosynthesis might require a technical and unintuitive explanation. Everything starts with [Rubisco](https://en.wikipedia.org/wiki/RuBisCO). The Rubisco enzyme grabs carbon dioxide from the atmosphere and incorporates it into sugars. Unfortunately this enzyme is prone to mistake oxygen for carbon dioxide. [When Rubisco incorporate oxygen instead of carbon dioxide into sugars](https://en.wikipedia.org/wiki/Photorespiration) it uses energy to produce waste and useless molecules, that must be recycled spending additional energy. The hotter the weather, the more likely is Rubisco to mistakes oxygen for carbon dioxide and thus to waste precious time and energy. In most plants the losses caused by mistaking oxygen for carbon dioxide neutralise the gains from photosynthesis -- sometimes in temperatures as low as 30° -- making photosynthesis almost useless in hot weather.

```
here some images of rubisco and photorespiration
```

C4 and CAM plants, have invented rather imaginative ways to boost photosynthesis in hot weather. Examples of [C4 plants](https://en.wikipedia.org/wiki/C4_carbon_fixation) are Maize, Sugar Cane, Millet; known [CAM plants](https://en.wikipedia.org/wiki/Crassulacean_acid_metabolism) are all the succulent plants, such as Pineapple, Agave, Aloe and the funny looking Opuntia.

```
panel with C4 and CAM plants
```

C4 plant boost photosynthesis by building a true molecular pump that concentrate carbon dioxide inside the inner layers of the leaf, so that this can be more easily converted into carbohydrate. CAM plants, instead, open pores and assimilate carbon dioxide from the atmosphere only at night, a strategy that at once allows to enrich carbon dioxide and to control water losses.

Both solutions are clever and complicated. How can we study them? How can we understand exactly what the plant does when it uses those kinds of photosynthesis? We can look at the microscope and observe anatomical changes in the leaves, we can measure gas exchange between the leaf and the atmosphere, we can grow a plant in different condition, at different temperatures, with different concentration of carbon dioxide in the air, in dry or wet environment, under different light intensities, and see how fast, well and healthy the plant grows. But if we want to know the details of the molecular machineries that constitute photosynthesis, things get small. At this point, it comes in handy molecular genetics.
