# Two Drastic Adaptations

Every plant species adapts photosynthesis to its needs with small modification to the photosynthetic machinery. But two drastic adaptation of the photosynthetic machinery are also known and they have been evolved by two groups of plants species. Those plants are known as C4 and CAM and they are adapted to grow and thrive in hot and dry weather.

Hot and dry weather is very hostile to photosynthesis, the reason why is technical and not at as intuitive as it might look.

Everything starts with [Rubisco](https://en.wikipedia.org/wiki/RuBisCO): the enzyme that in photosynthesis grabs carbon dioxide from the environment and incorporates it into sugars. Unfortunately, Rubisco is prone to mistake oxygen for carbon dioxide. [When Rubisco incorporate oxygen instead of carbon dioxide into sugars](https://en.wikipedia.org/wiki/Photorespiration) it uses energy to produce waste and useless molecules that must be recycled spending additional energy. The hotter the weather, the more Rubisco mistakes oxygen for carbon dioxide. In most plants the losses caused by these mistakes neutralize the gains from photosynthesis in temperatures as low as 30°, making photosynthesis almost useless in hot weather.

```
here some images of rubisco and photorespiration
```

C4 and CAM plants, have invented rather imaginative ways to boost photosynthesis in hot weather. Examples of [C4 plants](https://en.wikipedia.org/wiki/C4_carbon_fixation) are Maize, Sugar Cane, Millet; known [CAM plants](https://en.wikipedia.org/wiki/Crassulacean_acid_metabolism) are all the succulent plants, such as Pineapple, Agave, Aloe and the funny looking Opuntia.

```
panel with C4 and CAM plants
```

C4 plant boost photosynthesis by building a true molecular pump that concentrate carbon dioxide inside the inner layers of the leaf, so that this can be more easily converted into carbohydrate. CAM plants, instead, open pores and assimilate carbon dioxide from the atmosphere only at night, a strategy that at once also allows to control water losses.

Both solutions are clever and complicated. How can we study them? How can we understand exactly what the plant does when it uses those kinds of photosynthesis? We can look at the microscope and check anatomical changes in the leaves, we can measure gas exchange between the leaf and the atmosphere, we can grow a plant in different condition, at different temperatures, with different concentration of carbon dioxide in the air, in dry or wet environment, under different light intensities, and see how fast the plant grows. But when we want to know the details of the components of the molecular machineries that constitute photosynthesis, things get very small, and complicated. At this point, it comes in handy molecular genetics.
